apiVersion: v1
kind: Service
metadata:
  name: kvdbservice
  labels:
    app: kvdb

spec:
  selector:
    app: kvdb
  clusterIP: None
  ports:
    - port: 11001
      name: kvdb-port
      protocol: TCP
      targetPort: 11001
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kvdbrep 
spec:
  serviceName: kvdbservice 
  replicas: 3
  selector:
    matchLabels:
      app: kvdb
  template:
    metadata:
      labels:
        app: kvdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kvdbserver
          image: localhost:5000/kvdb:latest
          env:
            - name: MISUBDOMINIO
              value: kvdbservice.default.svc.cluster.local
            - name: MINOMBREPOD
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
          command: # Si es el primer nodo, kvdb-0, se lanza sin la opción -j
            - sh
            - "-c"
            - |
              echo $(MINOMBREPOD) | grep -qE '[^0-9]+0$'
              if [ $? -eq 0 ]; then
                /kvdb -n $(MINOMBREPOD) -a $(MINOMBREPOD).$(MISUBDOMINIO):11001
              else
                /kvdb -n $(MINOMBREPOD) -a $(MINOMBREPOD).$(MISUBDOMINIO):11001 -j kvdbrep-0.$(MISUBDOMINIO):11001
              fi 
          ports:
            - containerPort: 11001